version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:7.16.3
    container_name: elasticsearch
    hostname: elasticsearch
#    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: kibana:7.16.3
#    restart: always
    hostname: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  apm_server:
    image: elastic/apm-server:7.16.3
    hostname: apm_server
    container_name: apm_server
    ports:
      - 8200:8200
    depends_on:
      - elasticsearch
volumes:
  elasticsearch_data:
